version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: chessbuddy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/chessbuddy
      CORS_ALLOW_ORIGINS: "*"
      ENGINE_PATH: /usr/bin/stockfish
      UVICORN_WORKERS: 2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

  bot:
    build: .
    command: python -m cbuddy.bot
    environment:
      API_BASE: http://api:8000
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - api
    restart: unless-stopped

volumes:
  pgdata:
